# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets, QtPrintSupport
from PyQt5.QtGui import QScreen
from PyQt5.Qt import QFileInfo
from PyQt5.QtPrintSupport import QPrintDialog, QPrinter, QPrintPreviewDialog
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QFileDialog, QSlider
from pandas.core.base import SpecificationError
from scipy import signal
import matplotlib.pyplot as plt
import numpy as np
import sys
import pandas as pd
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
import os
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
import matplotlib
from pyqtgraph.widgets.ComboBox import ComboBox
import pyqtgraph.exporters
matplotlib.use('Qt5Agg')


class Ui_MainWindow(object):
    def __init__(self,*args, **kwargs):
        super().__init__()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.play_botton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.play_botton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon_images/play.jpeg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_botton.setIcon(icon)
        self.play_botton.setIconSize(QtCore.QSize(16, 20))
        self.play_botton.setCheckable(False)
        self.play_botton.setObjectName("play_botton")
        self.horizontalLayout.addWidget(self.play_botton)
        self.pause_botton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pause_botton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon_images/pause.jpeg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_botton.setIcon(icon1)
        self.pause_botton.setIconSize(QtCore.QSize(40, 20))
        self.pause_botton.setObjectName("pause_botton")
        self.horizontalLayout.addWidget(self.pause_botton)
        self.zoom_in_botton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zoom_in_botton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon_images/zoom_in.jpeg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in_botton.setIcon(icon2)
        self.zoom_in_botton.setIconSize(QtCore.QSize(40, 20))
        self.zoom_in_botton.setObjectName("zoom_in_botton")
        self.horizontalLayout.addWidget(self.zoom_in_botton)
        self.zoom_out_botton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zoom_out_botton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon_images/zoom_out.jpeg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out_botton.setIcon(icon3)
        self.zoom_out_botton.setIconSize(QtCore.QSize(40, 20))
        self.zoom_out_botton.setObjectName("zoom_out_botton")
        self.horizontalLayout.addWidget(self.zoom_out_botton)
        self.show_botton = QtWidgets.QPushButton(self.centralwidget)
        self.show_botton.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_botton.setFont(font)
        self.show_botton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon_images/show.jpeg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_botton.setIcon(icon4)
        self.show_botton.setIconSize(QtCore.QSize(0, 0))
        self.show_botton.setObjectName("show_botton")
        self.horizontalLayout.addWidget(self.show_botton)
        self.hide_botton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.hide_botton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon_images/hide.jpeg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hide_botton.setIcon(icon5)
        self.hide_botton.setObjectName("hide_botton")
        self.horizontalLayout.addWidget(self.hide_botton)
        self.spectrogram_botton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spectrogram_botton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon_images/spectogram.jpeg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.spectrogram_botton.setIcon(icon6)
        self.spectrogram_botton.setObjectName("spectrogram_botton")
        self.horizontalLayout.addWidget(self.spectrogram_botton)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.main_graph = QtWidgets.QGraphicsView(self.widget)
        self.main_graph.setEnabled(True)
        self.main_graph.setMouseTracking(False)
        self.main_graph.setTabletTracking(False)
        self.main_graph.setAutoFillBackground(False)
        self.main_graph.setObjectName("main_graph")
        self.horizontalLayout_5.addWidget(self.main_graph)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.EMG_label = QtWidgets.QLabel(self.widget)
        self.EMG_label.setAlignment(QtCore.Qt.AlignCenter)
        self.EMG_label.setObjectName("EMG_label")
        self.verticalLayout_3.addWidget(self.EMG_label)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.ECG_label = QtWidgets.QLabel(self.widget)
        self.ECG_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ECG_label.setObjectName("ECG_label")
        self.verticalLayout_3.addWidget(self.ECG_label)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.EOG_label = QtWidgets.QLabel(self.widget)
        self.EOG_label.setAlignment(QtCore.Qt.AlignCenter)
        self.EOG_label.setObjectName("EOG_label")
        self.verticalLayout_3.addWidget(self.EOG_label)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.signal_1_color_box = QtWidgets.QComboBox(self.widget)
        self.signal_1_color_box.setObjectName("signal_1_color_box")
        self.signal_1_color_box.addItem("")
        self.signal_1_color_box.addItem("")
        self.signal_1_color_box.addItem("")
        self.signal_1_color_box.addItem("")
        self.verticalLayout_6.addWidget(self.signal_1_color_box)
        self.dignal_2_color_box = QtWidgets.QComboBox(self.widget)
        self.dignal_2_color_box.setObjectName("dignal_2_color_box")
        self.dignal_2_color_box.addItem("")
        self.dignal_2_color_box.addItem("")
        self.dignal_2_color_box.addItem("")
        self.dignal_2_color_box.addItem("")
        self.verticalLayout_6.addWidget(self.dignal_2_color_box)
        self.signal_3_color_box = QtWidgets.QComboBox(self.widget)
        self.signal_3_color_box.setObjectName("signal_3_color_box")
        self.signal_3_color_box.addItem("")
        self.signal_3_color_box.addItem("")
        self.signal_3_color_box.addItem("")
        self.signal_3_color_box.addItem("")
        self.verticalLayout_6.addWidget(self.signal_3_color_box)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.widget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.verticalScrollBar.setMaximum()
        self.verticalScrollBar.setMinimum()
        self.horizontalLayout_5.addWidget(self.verticalScrollBar)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.widget)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalScrollBar.setMaximum()
        self.horizontalScrollBar.setMinimum()
        self.verticalLayout.addWidget(self.horizontalScrollBar)
        self.speed_slider = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.speed_slider.sizePolicy().hasHeightForWidth())
        self.speed_slider.setSizePolicy(sizePolicy)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.verticalLayout.addWidget(self.speed_slider)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spectrogram = QtWidgets.QGraphicsView(self.widget_2)
        self.spectrogram.setObjectName("spectrogram")
        self.horizontalLayout_2.addWidget(self.spectrogram)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.color_paletta_box = QtWidgets.QComboBox(self.widget_2)
        self.color_paletta_box.setAutoFillBackground(False)
        self.color_paletta_box.setObjectName("color_paletta_box")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon_images/palette.jpeg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.color_paletta_box.addItem(icon7, "")
        self.color_paletta_box.addItem("")
        self.color_paletta_box.addItem("")
        self.color_paletta_box.addItem("")
        self.color_paletta_box.addItem("")
        self.color_paletta_box.addItem("")
        self.horizontalLayout_3.addWidget(self.color_paletta_box)
        self.contrast_max_slider = QtWidgets.QSlider(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.contrast_max_slider.sizePolicy().hasHeightForWidth())
        self.contrast_max_slider.setSizePolicy(sizePolicy)
        self.contrast_max_slider.setOrientation(QtCore.Qt.Vertical)
        self.contrast_max_slider.setInvertedAppearance(True)
        self.contrast_max_slider.setObjectName("contrast_max_slider")
        self.horizontalLayout_3.addWidget(self.contrast_max_slider)
        self.contrast_min_slider = QtWidgets.QSlider(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.contrast_min_slider.sizePolicy().hasHeightForWidth())
        self.contrast_min_slider.setSizePolicy(sizePolicy)
        self.contrast_min_slider.setOrientation(QtCore.Qt.Vertical)
        self.contrast_min_slider.setObjectName("contrast_min_slider")
        self.horizontalLayout_3.addWidget(self.contrast_min_slider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.signal_choice_box = QtWidgets.QComboBox(self.widget_2)
        self.signal_choice_box.setObjectName("signal_choice_box")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(
            "icon_images/change_signal.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signal_choice_box.addItem(icon8, "")
        self.signal_choice_box.addItem("")
        self.signal_choice_box.addItem("")
        self.signal_choice_box.addItem("")
        self.horizontalLayout_4.addWidget(self.signal_choice_box)
        self.submit_botton = QtWidgets.QPushButton(self.widget_2)
        self.submit_botton.setObjectName("submit_botton")
        self.horizontalLayout_4.addWidget(self.submit_botton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Save_As_PDF_action = QtWidgets.QAction(MainWindow)
        self.Save_As_PDF_action.setObjectName("Save_As_PDF_action")
        self.actionChannel_2 = QtWidgets.QAction(MainWindow)
        self.actionChannel_2.setObjectName("actionChannel_2")
        self.actionChannel_1 = QtWidgets.QAction(MainWindow)
        self.actionChannel_1.setObjectName("actionChannel_1")
        self.actionChannel_3 = QtWidgets.QAction(MainWindow)
        self.actionChannel_3.setObjectName("actionChannel_3")
        self.actionChannel_4 = QtWidgets.QAction(MainWindow)
        self.actionChannel_4.setObjectName("actionChannel_4")
        self.Open_Signals_actoin = QtWidgets.QAction(MainWindow)
        self.Open_Signals_actoin.setObjectName("Open_Signals_actoin")
        self.menufile.addAction(self.Open_Signals_actoin)
        self.menufile.addSeparator()
        self.menufile.addAction(self.Save_As_PDF_action)
        self.menubar.addAction(self.menufile.menuAction())

        self.pen1 = pg.mkPen((255, 0, 0), width=3)
        self.pen2 = pg.mkPen((0, 255, 0), width=3)
        self.pen3 = pg.mkPen((0, 0, 255), width=3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play_botton.setText(_translate("MainWindow", "Play"))
        self.pause_botton.setText(_translate("MainWindow", "Pause"))
        self.zoom_in_botton.setText(_translate("MainWindow", "Zoom In"))
        self.zoom_out_botton.setText(_translate("MainWindow", "Zoom Out"))
        self.show_botton.setText(_translate("MainWindow", "Show"))
        self.hide_botton.setText(_translate("MainWindow", "Hide"))
        self.spectrogram_botton.setText(_translate("MainWindow", "SPECT"))
        self.EMG_label.setText(_translate("MainWindow", "EMG"))
        self.ECG_label.setText(_translate("MainWindow", "ECG"))
        self.EOG_label.setText(_translate("MainWindow", "EOG"))
        self.signal_1_color_box.setItemText(
            0, _translate("MainWindow", "signal 1 color"))
        self.signal_1_color_box.setItemText(1, _translate("MainWindow", "RED"))
        self.signal_1_color_box.setItemText(
            2, _translate("MainWindow", "BLUE"))
        self.signal_1_color_box.setItemText(
            3, _translate("MainWindow", "GREEN"))
        self.dignal_2_color_box.setItemText(
            0, _translate("MainWindow", "signal 2 color"))
        self.dignal_2_color_box.setItemText(1, _translate("MainWindow", "RED"))
        self.dignal_2_color_box.setItemText(
            2, _translate("MainWindow", "BLUE"))
        self.dignal_2_color_box.setItemText(
            3, _translate("MainWindow", "GREEN"))
        self.signal_3_color_box.setItemText(
            0, _translate("MainWindow", "signal 3 color"))
        self.signal_3_color_box.setItemText(1, _translate("MainWindow", "RED"))
        self.signal_3_color_box.setItemText(
            2, _translate("MainWindow", "BLUE"))
        self.signal_3_color_box.setItemText(
            3, _translate("MainWindow", "GREEN"))
        self.color_paletta_box.setItemText(
            0, _translate("MainWindow", " palettes"))
        self.color_paletta_box.setItemText(
            1, _translate("MainWindow", "Viridis"))
        self.color_paletta_box.setItemText(
            2, _translate("MainWindow", "Inferno"))
        self.color_paletta_box.setItemText(
            3, _translate("MainWindow", "Magma"))
        self.color_paletta_box.setItemText(
            4, _translate("MainWindow", "Cividis"))
        self.color_paletta_box.setItemText(
            5, _translate("MainWindow", "Plasma"))
        self.signal_choice_box.setItemText(
            0, _translate("MainWindow", "Choose Signal"))
        self.signal_choice_box.setItemText(1, _translate("MainWindow", "ECG"))
        self.signal_choice_box.setItemText(2, _translate("MainWindow", "EMG"))
        self.signal_choice_box.setItemText(3, _translate("MainWindow", "EOG"))
        self.submit_botton.setText(_translate("MainWindow", "Submit"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.Save_As_PDF_action.setText(
            _translate("MainWindow", "Save As PDF"))
        self.actionChannel_2.setText(_translate("MainWindow", "Channel 2"))
        self.actionChannel_1.setText(_translate("MainWindow", "Channel 1 "))
        self.actionChannel_3.setText(_translate("MainWindow", "Channel 2"))
        self.actionChannel_4.setText(_translate("MainWindow", "Channel 3"))
        self.Open_Signals_actoin.setText(
            _translate("MainWindow", "Open Signals"))

    def Change_signal1_color(self):
        color1 = self.signal_1_color_box.currentText()
        if color1 == "RED":
            self.pen1 = pg.mkPen((255, 0, 0), width=3)
        elif color1 == "BLUE":
            self.pen1 = pg.mkPen((0, 0, 255), width=3)
        elif color1 == "GREEN":
            self.pen1 = pg.mkPen((0, 255, 0), width=3)

    def Change_signal2_color(self):
        color2 = self.dignal_2_color_box.currentText()
        if color2 == "RED":
            self.pen2 = pg.mkPen((255, 0, 0), width=3)
        elif color2 == "BLUE":
            self.pen2 = pg.mkPen((0, 0, 255), width=3)
        elif color2 == "GREEN":
            self.pen2 = pg.mkPen((0, 255, 0), width=3)

    def Change_signal3_color(self):
        color3 = self.signal_3_color_box.currentText()
        if color3 == "RED":
            self.pen3 = pg.mkPen((255, 0, 0), width=3)
        elif color3 == "BLUE":
            self.pen3 = pg.mkPen((0, 0, 255), width=3)
        elif color3 == "GREEN":
            self.pen3 = pg.mkPen((0, 255, 0), width=3)

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
